# Make sure you set DOCKER_HOST_IP environment variable

version: '3.7'

services:
  engine:
    container_name: epi-engine
    image: epi-engine:latest
    build:
      context: ../engine
    environment:
      RUST_LOG: INFO
      EPI_KAFKA_URL: "kafka:29092"
    command: cargo run --release -- --daemon

  server:
    image: epi-web:latest
    container_name: epi-server
    build:
     context: ../web
    environment:
      DATABASE_URL: "mongodb://mongodb_container:27018/local_database"
      KAFKA_URL: "kafka:29092"
    working_dir: /web
    command: npm start
    ports:
      - "3000:3000"

  kafka-consumer:
    image: epi-consumer:latest
    container_name: epi-kafka-consumers
    environment:
      DATABASE_URL: "mongodb://mongodb_container:27018/local_database"
      KAFKA_URL: "kafka:29092"
    build:
      context: ../web
    working_dir: /web/server  
    command: npm run start-consumers

