---
small_pox:
  regular_transmission_start_day: 10
  high_transmission_start_day: 16
  last_day: 22
  asymptomatic_last_day: 22
  mild_infected_last_day: 22
  regular_transmission_rate: 0.05
  high_transmission_rate: 0.5
  death_rate: 0.2
  percentage_asymptomatic_population: 0.0
  percentage_severe_infected_population: 1.0
  exposed_duration: 0
  pre_symptomatic_duration: 0

sars: #Guesstimated
  regular_transmission_start_day: 5
  high_transmission_start_day: 10
  last_day: 23
  asymptomatic_last_day: 23
  mild_infected_last_day: 23
  regular_transmission_rate: 0.025
  high_transmission_rate: 0.25
  death_rate: 0.1
  percentage_asymptomatic_population: 0.0
  percentage_severe_infected_population: 1.0
  exposed_duration: 0
  pre_symptomatic_duration: 0

covid_19: #Guesstimated
  regular_transmission_start_day: 5
  high_transmission_start_day: 20
  last_day: 26
  asymptomatic_last_day: 9
  mild_infected_last_day: 12
  regular_transmission_rate: 0.025
  high_transmission_rate: 0.25
  death_rate: 0.035
  percentage_asymptomatic_population: 0.3
  percentage_severe_infected_population: 0.3
  exposed_duration: 48
  pre_symptomatic_duration: 48
